// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Todo defines model for Todo.
type Todo struct {
	Completed   *bool     `json:"completed,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	Description *string   `json:"description,omitempty"`
	Id          int       `json:"id"`
	Title       string    `json:"title"`
}

// TodoInput defines model for TodoInput.
type TodoInput struct {
	Completed   *bool   `json:"completed,omitempty"`
	Description *string `json:"description,omitempty"`
	Title       string  `json:"title"`
}

// GetTodosParams defines parameters for GetTodos.
type GetTodosParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostTodosJSONRequestBody defines body for PostTodos for application/json ContentType.
type PostTodosJSONRequestBody = TodoInput

// PutTodosTodoIdJSONRequestBody defines body for PutTodosTodoId for application/json ContentType.
type PutTodosTodoIdJSONRequestBody = TodoInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all TODO items
	// (GET /todos)
	GetTodos(ctx echo.Context, params GetTodosParams) error
	// Create a new TODO item
	// (POST /todos)
	PostTodos(ctx echo.Context) error
	// Delete a TODO item
	// (DELETE /todos/{todoId})
	DeleteTodosTodoId(ctx echo.Context, todoId int) error
	// Get a specific TODO item
	// (GET /todos/{todoId})
	GetTodosTodoId(ctx echo.Context, todoId int) error
	// Update a TODO item
	// (PUT /todos/{todoId})
	PutTodosTodoId(ctx echo.Context, todoId int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetTodos converts echo context to params.
func (w *ServerInterfaceWrapper) GetTodos(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTodosParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTodos(ctx, params)
	return err
}

// PostTodos converts echo context to params.
func (w *ServerInterfaceWrapper) PostTodos(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTodos(ctx)
	return err
}

// DeleteTodosTodoId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTodosTodoId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "todoId" -------------
	var todoId int

	err = runtime.BindStyledParameterWithOptions("simple", "todoId", ctx.Param("todoId"), &todoId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter todoId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTodosTodoId(ctx, todoId)
	return err
}

// GetTodosTodoId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTodosTodoId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "todoId" -------------
	var todoId int

	err = runtime.BindStyledParameterWithOptions("simple", "todoId", ctx.Param("todoId"), &todoId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter todoId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTodosTodoId(ctx, todoId)
	return err
}

// PutTodosTodoId converts echo context to params.
func (w *ServerInterfaceWrapper) PutTodosTodoId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "todoId" -------------
	var todoId int

	err = runtime.BindStyledParameterWithOptions("simple", "todoId", ctx.Param("todoId"), &todoId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter todoId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutTodosTodoId(ctx, todoId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/todos", wrapper.GetTodos)
	router.POST(baseURL+"/todos", wrapper.PostTodos)
	router.DELETE(baseURL+"/todos/:todoId", wrapper.DeleteTodosTodoId)
	router.GET(baseURL+"/todos/:todoId", wrapper.GetTodosTodoId)
	router.PUT(baseURL+"/todos/:todoId", wrapper.PutTodosTodoId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RWy27bMBD8FWLbI2vJTU68pQ0QGCiQAE1PQQ6MtHIYiI+QqzSGoX8vlnJs+dE2fbkn",
	"ScxwdzgzG3oJlbfBO3SUQC0hVfdodX699rXnp27bywbUzRLeRmxAwZtis6dYbSgYPXOhI+jlEkL0ASMZ",
	"zJWqiJqwPiP+aHy0mkBBrQnfkbEIEmgREBQkisbNoZdgasaulo0jnGOEvpcQ8bEzEWtQNwySo+K36zr+",
	"7gErgv62l7AhpvZ4eRtaJBz3uvO+Re2YQ42piiaQ8W4E2HAkQy0e+MsOywG2T45xxjVZ461WcCaSYWbi",
	"7GomyAurnZ6juL48vxSG0CZYN4e8+MkkYjBIeMKYhirTSTkpmacP6HQwoOBkUk5OQELQdJ8VKMjXPr/N",
	"MQvE8mimMatBwQXSdQbwlqgtEsaUo2C4w2OHcQESnLZMpTXWEMhVhria1c/GdhbUtCwlWONWX3Lf2VsW",
	"LQXv0uDN+7IcLHKELlPTIbSmyuSKhzR4smk16KJ+HtLs3NBdx6gXgxHbBnzuqgpTarpWvJDKtqbOWh0X",
	"oCArrtt2bEovIfh0QMYrn9Y6cjIw0QdfL37pfK+cve3wUeyw3xN2+lcbH9Lv4zCTO5oNq0ILh183umXQ",
	"kMNiyY9Z3Q8jwaO5L+Z5Xs9y5nPX3wknZ3yTTXqBboszDusrInm6P6ujqGTGvNpLOD2EXZ9ZOE+i8Z3b",
	"lWg4nNBjeeSPZ/PoIpT/PD4Hx++3Nb1AElqkgJVpTLWt7Opa2BnX7njK/vd/Bkd1swt86f+Bl19yge35",
	"yAiMTy/2dLEFBfdEIami0MFM8FnzdTqpvC2epvyz4FsAAAD//5huJNz3CAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
